services:
  pubsub:
    container_name: emu-pubsub
    image: 'google/cloud-sdk:emulators'
    command: 'gcloud --user-output-enabled --log-http beta emulators pubsub start --project=fake --host-port=0.0.0.0:8085'
    ports:
      - '8085:8085'

  firestore:
    container_name: emu-firestore
    image: 'google/cloud-sdk:emulators'
    command: 'gcloud --user-output-enabled --log-http beta emulators firestore start --project=fake --host-port=0.0.0.0:8086'
    ports:
      - '8086:8086'

  bigquery:
    container_name: emu-bigquery
    platform: linux/amd64
    image: 'ghcr.io/goccy/bigquery-emulator:latest'
    command: '/bigquery-emulator --project=fake' 
    ports:
      - '9050:9050' // Rest API
      #- '9060:9060' // gRPC API

networks:
  default:
    name: 'emulators'
