services:
  pubsub:
    container_name: emu-pubsub
    image: 'google/cloud-sdk:510.0.0-emulators'
    command: 'gcloud --user-output-enabled --log-http beta emulators pubsub start --project=${GCP_PROJECT_ID:-fake} --host-port=0.0.0.0:8085'
    ports:
      - '8085:8085'

  # firestore:
  #   container_name: emu-firestore
  #   image: 'google/cloud-sdk:emulators'
  #   command: 'gcloud --user-output-enabled --log-http beta emulators firestore start --project=${GCP_PROJECT_ID:-fake} --host-port=0.0.0.0:8086'
  #   ports:
  #     - '8086:8086'

networks:
  default:
    name: 'emulators'
