services:
  pubsub:
    container_name: emu-pubsub
    image: 'google/cloud-sdk:emulators'
    command: 'gcloud --user-output-enabled --log-http beta emulators pubsub start --project=fake --host-port=0.0.0.0:8085'
    ports:
      - '8085:8085'

  firestore:
    container_name: emu-firestore
    image: 'google/cloud-sdk:emulators'
    command: 'gcloud --user-output-enabled --log-http beta emulators firestore start --project=fake --host-port=0.0.0.0:8086'
    ports:
      - '8086:8086'

  bigquery:
    container_name: emu-bigquery
    image: 'ghcr.io/goccy/bigquery-emulator:latest'
    command: '/bigquery-emulator --project=fake' 
    ports:
      - '9050' # Rest API
      - '9060' # gRPC API

  bigquery-proxy:
    container_name: bigquery-proxy
    image: caddy:2.10.0
    ports:
      - "9050:9050"
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:

networks:
  default:
    name: 'emulators'
