[package]
name = "pubsub2bq"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "^1", features = ["full"] }
axum = { version = "^0.8" }
reqwest = { version = "0.12.15", features = ["json"] }